name: "Update work item state - PR Open and Merge"
description: "This action will update work item state in Boards within Azure DevOps when the PR is merged"
author: "Canarys Automations, Marcin Gadomski"
branding:
  icon: "git-pull-request"
  color: "black"
outputs:
  id:
    description: "Work item state updated"
runs:
  using: "node12"
  main: "index.js"
